spdm-claims = {
  &(measurements: 1) => {
    + block-id => spdm-measurement
  }
  &(certificates: 2) => [
    device-cert: cert
    device-cert-chain: cert-chain
    ? aux-cert-chains: {
      + slot-id: cert-chain
    }
  ]
  ? &(signature: 3) => spdm-measurement-blocks-signature
}

cert = bytes ; TODO(mathieu) is this PEM or DER?
cert-chain = [ + cert ]
block-id = 0..254 ; TODO(mathieu) is the upper bound 250 instead?
slot-id = 1..7
