certificate-log-label = 10001

;
; GET_CERTIFICATE message is used to get the certificate chain for a
; specific slot.
;
certificate-chain = {
    &(certificate-slot: 1) => 1..7
    &(certificate-chain: 2) => bytes
}
certificate-chain-array = [ 1*7 certificate-chain ]

certificate-log = (
    certificate-log-label => certificate-chain-array
)
