da-eat-claims = (da-eat-claim-map)

;
; A device claim is composed of a certificate log and a
; measurement log
;
spdm-device-claim-map = {
    certificate-log
    ? measurement-log
    ? $$device-interface-log
}

;
; Devices discovered from other busses such as CXL and AMBA CHI
; can also be allocated to a CVM but for now,  we only support
; PCIe devices that enact the SPDM protocol.
;
device-claim-array = [ + spdm-device-claim-map / $$cxl-device-claim-map / $$chi-device-claim-map ]

;
; Several devices can be assigned to a VM
;
device-log-label = 10000
device-log = (
    device-log-label => device-claim-array
)

da-eat-claim-map = {
    claims-profile,
    device-log
}
